server:
  port: 7004

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tickets
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: TICKET-SERVICE
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
